name: open_api_plus
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications. Fork, with a couple of fixes and null safety by @hpoul
version: 3.0.1
#homepage: https://github.com/stablekernel/open-api-dart
#homepage: https://github.com/hpoul/open-api-dart
homepage: https://github.com/t-unit/open_api_dart_plus
#author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ^3.3.0

dependencies:
  codable_plus: ^1.0.1
  meta: ">=1.3.0 <2.0.0"

dev_dependencies:
  test: ">=1.16.4 <2.0.0"
  lints: ^3.0.0
